(function(){
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function tabs(active){return `<nav class="subnav"><a class="${active==='venue'?'active':''}" href="#/rules/venue">场馆动线</a><a class="${active==='replacement'?'active':''}" href="#/rules/replacement">动作替换</a><a class="${active==='conflicts'?'active':''}" href="#/rules/conflicts">冲突检查</a></nav>`;}
  function hero(title,body){return `<section class="view-hero compact"><span class="eyebrow">PROGRAMMING RULES</span><h1>${esc(title)}</h1><p>${esc(body)}</p></section>`;}
  function copyControl(id,title,lines){const api=window.V14ModuleCopy;if(!api)return '';api.register(id,'knowledge',{title,lines});return `<div class="module-copy-row page-module-copy">${api.button(id,'复制本模块')}</div>`;}
  function venue(){const copy=copyControl('rules-venue','场馆动线规则',['2F PREP：泡沫轴、动态伸展、目标激活。完成后再下楼。','1F STRENGTH：A / B / C + D1 / D2 / CORE。进入力量阶段后不再返回 2F。','2F RECOVERY：力量结束后统一上楼拉伸恢复。','POST CARDIO：跑步机 / 楼梯机独立执行，不计入 F111 正式力量模板。']);return tabs('venue')+hero('场馆动线规则','正式力量课只允许一次下楼、一次上楼；跑步机和楼梯机只属于课后有氧。')+copy+`<section class="section-card"><div class="route-rule"><div><b>01</b><h3>2F PREP</h3><p>泡沫轴、动态伸展、目标激活。完成后再下楼。</p></div><i>↓</i><div><b>02</b><h3>1F STRENGTH</h3><p>A / B / C + D1 / D2 / CORE。进入力量阶段后不再返回 2F。</p></div><i>↑</i><div><b>03</b><h3>2F RECOVERY</h3><p>力量结束后统一上楼拉伸恢复。</p></div><i>→</i><div><b>04</b><h3>POST CARDIO</h3><p>跑步机 / 楼梯机独立执行，不计入 F111 正式力量模板。</p></div></div></section>`;}
  function replacement(){const copy=copyControl('rules-replacement','动作替换规则',['1. 同动作模式：优先保持原槽位的动作模式。','2. 同 V1.1 层级：默认优先同级替换；进退阶必须明确标记。','3. 场馆路由允许：正式 1F 训练只能进入 1F_ONLY 或 FLEX_1F_2F。','4. 可自动编排：来源动作必须已允许自动编排，或属于 SUPPORT / CORE Canon。','5. 排除重复：替换后不能在同一正式训练块重复标准动作。','6. 来源与系统分开：Excel 来源指定替代与系统推导替代不混成同一来源。']);return tabs('replacement')+hero('动作替换规则','替换优先解决“同一训练目的下的可执行替代”，不是把整张替换矩阵铺在课程页面。')+copy+`<section class="rule-grid"><article><b>1</b><h3>同动作模式</h3><p>优先保持原槽位的动作模式。</p></article><article><b>2</b><h3>同 V1.1 层级</h3><p>默认优先同级替换；进退阶必须明确标记。</p></article><article><b>3</b><h3>场馆路由允许</h3><p>正式 1F 训练只能进入 1F_ONLY 或 FLEX_1F_2F。</p></article><article><b>4</b><h3>可自动编排</h3><p>来源动作必须已允许自动编排，或属于 SUPPORT / CORE Canon。</p></article><article><b>5</b><h3>排除重复</h3><p>替换后不能在同一正式训练块重复标准动作。</p></article><article><b>6</b><h3>来源与系统分开</h3><p>Excel 来源指定替代与系统推导替代不混成同一来源。</p></article></section><section class="section-card"><h2 class="small-title">查看完整矩阵</h2><p class="muted-copy">完整替换矩阵保留为系统数据与维护资料。日常教练使用时，只在动作详情里展示当前动作的同级、退阶和进阶。</p><a class="text-link" href="#/maintenance">进入系统维护 →</a></section>`;}
  function conflicts(){const copy=copyControl('rules-conflicts','替换后冲突检查',['FAIL｜动作重复：同一正式训练块出现重复标准动作。','FAIL｜楼层冲突：非 1F_ONLY / FLEX 动作进入正式力量块。','FAIL｜编排状态：动作不允许自动编排。','WARN｜模式 / 层级改变：替换改变原动作模式或 V1.1 T 层级。','WARN｜负荷 / 器械集中：单一模式、负荷家族或器械被明显堆叠。','INFO｜SUPPORT / CORE 调整：进退阶和 Core Demand 改变会被明确提示。']);return tabs('conflicts')+hero('替换后冲突检查','每次替换后即时重算，区分硬冲突、警告和信息提示。')+copy+`<section class="rule-grid conflict-rules"><article class="hard"><b>FAIL</b><h3>动作重复</h3><p>同一正式训练块出现重复标准动作。</p></article><article class="hard"><b>FAIL</b><h3>楼层冲突</h3><p>非 1F_ONLY / FLEX 动作进入正式力量块。</p></article><article class="hard"><b>FAIL</b><h3>编排状态</h3><p>动作不允许自动编排。</p></article><article class="warn"><b>WARN</b><h3>模式 / 层级改变</h3><p>替换改变原动作模式或 V1.1 T 层级。</p></article><article class="warn"><b>WARN</b><h3>负荷 / 器械集中</h3><p>单一模式、负荷家族或器械被明显堆叠。</p></article><article><b>INFO</b><h3>SUPPORT / CORE 调整</h3><p>进退阶和 Core Demand 改变会被明确提示。</p></article></section>`;}
  function render(route){const p=route.page||'venue';if(p==='replacement')return replacement();if(p==='conflicts')return conflicts();return venue();}
  window.V14Views=window.V14Views||{};window.V14Views.rules=render;
})();
