(function(){
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const D=()=>window.V14_DATA;
  let filters={q:'',pattern:'',tier:'',zone:'',equipment:'',category:'',status:''};
  function uniq(key){return [...new Set(Object.values(D().actions).map(a=>a[key]).filter(Boolean))].sort();}
  function opts(values,label){return `<option value="">${label}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');}
  function filterActions(f=filters){return Object.values(D().actions).filter(a=>{
    const detail=D().actionDetails[a.id]?.fields||{};
    const hay=[a.name,a.id,a.pattern,a.tier,a.sourceTier,a.equipment,a.zone,a.routeLabel,a.category,detail['训练目标'],detail['教练口令']].join(' ').toLowerCase();
    if(f.q&&!hay.includes(f.q.toLowerCase()))return false;
    if(f.pattern&&a.pattern!==f.pattern)return false;if(f.tier&&a.tier!==f.tier)return false;if(f.zone&&(a.zone||a.routeLabel)!==f.zone)return false;if(f.equipment&&a.equipment!==f.equipment)return false;if(f.category&&a.category!==f.category)return false;if(f.status&&a.status!==f.status)return false;return true;
  });}
  function resultsHtml(items){return items.slice(0,180).map(a=>`<button class="action-row" type="button" data-action-id="${esc(a.id)}"><div><b>${esc(a.name)}</b><span>${esc(a.pattern||'未分类')} · ${esc(a.tier||a.sourceTier||'未标')}</span></div><div class="action-row-meta"><span>${esc(a.equipment||'')}</span><small>${esc(a.routeLabel||'')}</small></div></button>`).join('')||'<div class="no-results">没有符合条件的动作。</div>';}
  function render(){const zones=uniq('zone').concat(uniq('routeLabel').filter(x=>!uniq('zone').includes(x)));const items=filterActions();return `<section class="view-hero compact"><span class="eyebrow">ACTION LIBRARY</span><h1>动作库</h1><p>默认以搜索和筛选进入动作详情，不再一次展开 165+ 张动作卡。</p></section><section class="section-card"><div class="library-controls"><input id="action-search" type="search" placeholder="搜索动作 / 器械 / 口令 / 目标" value="${esc(filters.q)}"><select data-filter="pattern">${opts(uniq('pattern'),'全部模式')}</select><select data-filter="tier">${opts(uniq('tier'),'全部 V1.1 层级')}</select><select data-filter="zone">${opts(zones,'全部区域 / 路由')}</select><select data-filter="equipment">${opts(uniq('equipment'),'全部器械')}</select><select data-filter="category">${opts(uniq('category'),'全部类别')}</select><select data-filter="status">${opts(uniq('status'),'全部编排状态')}</select></div><div class="library-result-head"><b id="library-count">${items.length} 个动作</b><span>点击动作查看详情、同级替换和进退阶</span></div><div id="action-results" class="action-results">${resultsHtml(items)}</div></section>`;}
  function bind(route){const rerender=()=>{const items=filterActions();document.getElementById('action-results').innerHTML=resultsHtml(items);document.getElementById('library-count').textContent=items.length+' 个动作';bindRows();};const search=document.getElementById('action-search');if(search)search.addEventListener('input',e=>{filters.q=e.target.value;rerender();});document.querySelectorAll('[data-filter]').forEach(sel=>{const key=sel.dataset.filter;sel.value=filters[key]||'';sel.addEventListener('change',e=>{filters[key]=e.target.value;rerender();});});function bindRows(){document.querySelectorAll('.action-row').forEach(btn=>btn.addEventListener('click',()=>window.V14ActionDetail.open(btn.dataset.actionId,{systemMode:window.V14State.getMode()==='system'})));}bindRows();if(route.query?.focus){window.V14ActionDetail.open(route.query.focus,{systemMode:window.V14State.getMode()==='system'});}}
  window.V14Library={render,filterActions};window.V14Views=window.V14Views||{};window.V14Views.library=()=>render();window.V14Bind=window.V14Bind||{};window.V14Bind.library=bind;
})();
