const fs=require('fs'),vm=require('vm'),assert=require('assert');
const memory={};
const sessionStorage={getItem:k=>memory[k]??null,setItem:(k,v)=>{memory[k]=String(v)},removeItem:k=>delete memory[k]};
const ctx={window:{},location:{hash:''},sessionStorage,URLSearchParams,console};ctx.window.addEventListener=()=>{};vm.createContext(ctx);
for(const file of ['data/system-data.js','js/router.js','js/state.js','js/composer.js','js/resolved-session.js','js/conflict-core.js','js/conflict-service.js','js/conflict-plugins/f111.js','js/conflict.js']) vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
const R=ctx.window.V14Router,S=ctx.window.V14State,C=ctx.window.V14Composer,F=ctx.window.V14Conflict;
const route=R.parseHash('#/coach/compose?lower=single_leg_hinge&upper=horizontal_push&level=L3');
assert.strictEqual(route.area,'coach'); assert.strictEqual(route.page,'compose'); assert.strictEqual(route.query.lower,'single_leg_hinge'); assert(R.isValid(route));
assert(R.isValid(R.parseHash('#/coach/f111-01/l3')));
S.setComposerSelection('F111-C-SLH-HP-L3','A','movement_db_single_leg_rdl');
assert.strictEqual(S.getComposerSelection('F111-C-SLH-HP-L3','A','fallback'),'movement_db_single_leg_rdl');
assert.strictEqual(S.getSelection('F111-01-L3','F111-01-L3__A'),ctx.window.V14_DATA.sessions['F111-01-L3'].slots[0].baselineId);
S.resetComposer('F111-C-SLH-HP-L3'); assert.strictEqual(S.getComposerSelection('F111-C-SLH-HP-L3','A','fallback'),'fallback');
const expanded=C.resolve({level:'L3',lowerMode:'single_leg_hinge',upperMode:'horizontal_push',includeExpandedSupport:true,selections:{C:'SUP-S5-01'}});
const result=F.evaluateComposer(expanded);
assert(result.issues.some(x=>x.code==='GRADE_OUTSIDE_NORMAL_WINDOW'&&x.severity==='warn'));
const dup=JSON.parse(JSON.stringify(C.resolve({level:'L3',lowerMode:'squat',upperMode:'horizontal_pull'})));
dup.slots[3]={slotKey:'D1',slotName:'D1｜下肢辅助',actionId:'hake_shendun',name:'哈克深蹲',tier:'T3',grade:'',coreDemand:''};
const dupResult=F.evaluateComposer(dup);
assert(dupResult.issues.some(x=>x.code==='AUX_PATTERN_DUPLICATION'&&x.severity==='warn'));
console.log('composer state/route/conflict: PASS');
