const fs=require('fs'),vm=require('vm'),assert=require('assert');
const memory={}; const sessionStorage={getItem:k=>memory[k]??null,setItem:(k,v)=>memory[k]=String(v)};
const ctx={window:{},sessionStorage,document:{body:{dataset:{}},querySelectorAll:()=>[],getElementById:()=>null},location:{hash:''},URLSearchParams,console,setTimeout:()=>{}};
ctx.window.addEventListener=()=>{}; vm.createContext(ctx);
for(const file of ['data/system-data.js','data/anatomy-data.js','js/state.js','js/anatomy.js','js/composer.js','js/conflict.js','js/module-copy.js','js/session-copy.js','js/views-coach.js']) vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
const H=ctx.window.V14CoachAnatomy,S=ctx.window.V14SessionCopy;
const c=H.composerContext({page:'compose',query:{level:'L3',lower:'single_leg_hinge',upper:'horizontal_push',core:'anti_extension'}});
const p=H.buildComposerCopyPayload(c);
assert.strictEqual(p.slots.length,6);
assert.strictEqual(p.slots[0].name,'独立哑铃单腿罗马尼亚硬拉');
assert.strictEqual(p.slots[0].tier,'T3');
assert(/RIR/.test(p.slots[0].prescription));
assert.strictEqual(p.slots[2].grade,'SUP-S3');
assert(/^CORE-L[23]$/.test(p.slots[5].grade));
const coach=S.formatCoach(p);
assert(coach.includes('A｜下肢主项｜独立哑铃单腿罗马尼亚硬拉｜T3'));
assert(coach.includes('C｜支撑模式｜'));
assert(coach.includes('｜SUP-S3'));
assert(/CORE｜核心模式｜.*｜CORE-L[23]/.test(coach));
assert(coach.includes('RIR'));
for(const hidden of ['eq-dumbbell','1F 专用','哑铃 + 哑铃架','movement_db_single_leg_rdl']) assert(!coach.includes(hidden),hidden);
const member=S.formatMember(p,{now:'2026-09-09T12:00:00+08:00'});
for(const hidden of ['T3','SUP-S3','CORE-L2','CORE-L3','RIR','movement_db_single_leg_rdl']) assert(!member.includes(hidden),hidden);
assert(member.includes('独立哑铃单腿罗马尼亚硬拉'));
assert(member.includes('单腿后侧链 × 上肢推 × 核心稳定'));
assert(member.includes('L3｜负重进阶'));
assert(member.includes('今日训练重点\n单腿后侧链 · 上肢推力 · 核心稳定'));
assert(member.includes('课后有氧｜约 30 分钟'));
assert(member.includes('平均心率 130 到 140 左右（燃烧脂肪心率）'));
assert(!member.includes('POST CARDIO ONLY'));
assert(/坐姿腿弯举[^\n]*\n   大腿后侧强化/.test(member),'structured anatomy should drive auxiliary purpose');

const preset=H.buildCopyPayload('F111-06-L3','F111-06','L3');
const presetMember=S.formatMember(preset,{now:'2026-09-09T12:00:00+08:00'});
assert(presetMember.includes('1. 哈克深蹲｜3 × 10\n   大腿与臀部力量'));
assert(presetMember.includes('2. 哑铃卧推｜3 × 10\n   上肢推力'));
assert(presetMember.includes('3. 高位平板交替触肩｜2–3 × 20–30 秒\n   核心稳定与身体控制'));
assert(presetMember.includes('4. 髋内收｜1 × 15\n   大腿内侧强化'));
assert(presetMember.includes('5. 绳索三头下压｜3 × 12\n   手臂后侧强化'));
assert(presetMember.includes('6. Pallof抗旋转推举｜2–3 × 6–10 / 侧\n   核心抗旋转'));
assert(presetMember.includes('核心激活：平板支撑'));

const hipL4=H.composerContext({page:'compose',query:{level:'L4',lower:'hip_extension',upper:'horizontal_pull',core:'anti_extension'}});
const hipPayload=H.buildComposerCopyPayload(hipL4);
assert.strictEqual(hipPayload.slots[0].name,'臀推停顿主项');
assert.strictEqual(hipPayload.slots[0].tier,'T4');
assert.strictEqual(hipPayload.slots[0].prescription,'3–4组 × 6–8次｜RIR 1–2');
const hipCoach=S.formatCoach(hipPayload);
const hipMember=S.formatMember(hipPayload,{now:'2026-09-09T12:00:00+08:00'});
assert(hipCoach.includes('A｜下肢主项｜臀推停顿主项｜T4'));
assert(hipCoach.includes('3–4组 × 6–8次｜RIR 1–2'));
assert(hipMember.includes('臀部力量 × 上肢拉 × 核心稳定'));
assert(hipMember.includes('L4｜完整能力'));
console.log('composer copy: PASS');
