const fs=require('fs'),assert=require('assert');
const css=fs.readFileSync('assets/app.css','utf8');
const drawer=fs.readFileSync('assets/replacement-drawer.css','utf8');
for(const token of ['.f111-compose-hero','.f111-compose-stepper','.f111-mode-grid','.f111-prep-grid .session-warmup-grid','.f111-strength-grid','.f111-demand-switch nav','.f111-replace-trigger','.f111-visually-hidden'])assert(css.includes(token),`missing frozen CSS token ${token}`);
for(const token of ['.f111-action-drawer-shell','.f111-drawer-group','.f111-drawer-action.is-disabled','.f111-drawer-open body'])assert(drawer.includes(token),`missing drawer CSS token ${token}`);
assert(drawer.includes('align-items:end'),'mobile replacement drawer must dock to the bottom');
assert(drawer.includes('height:min(88dvh,760px)'),'mobile replacement drawer must leave the top edge visible');
assert(drawer.includes('border-radius:18px 18px 0 0'),'mobile replacement drawer must read as a bottom sheet');
assert(drawer.includes('grid-template-columns:minmax(0,1fr) auto'),'replacement candidates must reserve a compact action column');
assert(drawer.includes('.replacement-drawer-card>button{grid-column:2;grid-row:1;'),'replacement action must sit beside the candidate title');
assert(drawer.includes('.replacement-drawer-card>*:not(.replacement-drawer-card-top):not(button){grid-column:1/-1}'),'candidate details must retain the full card width');
const desktopDrawerCss=drawer.split('@media(max-width:620px)')[0];
assert(/\.replacement-drawer-card\{[^}]*grid-template-columns:minmax\(0,1fr\) auto;/.test(desktopDrawerCss),'desktop replacement cards must reserve a compact action column');
assert(/\.replacement-drawer-card>button\{[^}]*grid-column:2;grid-row:1;/.test(desktopDrawerCss),'desktop replacement action must sit beside the candidate title');
assert(desktopDrawerCss.includes('.replacement-drawer-card>*:not(.replacement-drawer-card-top):not(button){grid-column:1/-1}'),'desktop candidate details must retain the full card width');
assert(drawer.includes('.replacement-drawer-card,.f111-drawer-action,.f111-drawer-option{border-color:var(--line);border-radius:14px;background:#fff}'),'replacement and grouped action choices must share a white bordered card surface');
assert(drawer.includes('.replacement-drawer-card.is-current,.f111-drawer-action.is-current,.f111-drawer-option.is-current{border-color:#d6c6f6;background:#faf7ff}'),'replacement and grouped action choices must share selected styling');
assert(drawer.includes('.f111-drawer-action b,.f111-drawer-option b{font-size:14px;line-height:1.35;overflow-wrap:anywhere}'),'grouped action labels must match replacement candidate title scale');
assert(css.includes('grid-template-columns:repeat(2,minmax(0,1fr))'),'mobile cards must use two columns');
assert(css.includes('font-size:14px;line-height:1.7'),'mobile hero body text must not be tiny');
assert(/\.f111-support-grid \.f111-slot-card\{[^}]*display:grid;[^}]*grid-template-columns:minmax\(0,1fr\)(?:;|\})/.test(css),'C/CORE mobile cards must expose their header items as a one-column grid');
assert(/\.f111-support-grid \.composer-slot-head\{[^}]*display:contents(?:;|\})/.test(css),'C/CORE mobile header must allow the selector to follow the action title');
assert(/\.f111-support-grid \.composer-slot-head>div\{[^}]*grid-row:1;[^}]*white-space:nowrap(?:;|\})/.test(css),'C/CORE mode and level labels must stay together on the first row');
assert(/\.f111-support-grid \.f111-slot-main\{[^}]*grid-row:2;/.test(css),'C/CORE selected action name must occupy the second row');
assert(/\.f111-support-grid \.f111-action-drawer-trigger\{[^}]*grid-row:3;[^}]*width:100%;[^}]*min-width:0/.test(css),'C/CORE selector must appear below the selected action name and use the full card width');
assert(/\.f111-support-grid \.f111-action-drawer-trigger\{[^}]*min-height:44px(?:;|\})/.test(css),'C/CORE mobile selector must retain a 44px touch target');
console.log('f111_mobile_css_contract_test: PASS');
