(function(){
  const M=window.V14CoachModules=window.V14CoachModules||{},C=M.Common;
  const {esc,D,hero,coachModeSwitch,copyToolbar}=C;
  function composeHref(current,overrides={}){const q={level:current.level,lower:current.lowerMode,upper:current.upperMode,core:current.coreDemand,...overrides};if(current.includeExpandedMain)q.em='1';if(current.includeExpandedSupport)q.es='1';if(current.includeExpandedCore)q.ec='1';for(const k of ['em','es','ec'])if(overrides[k]===null)delete q[k];return '#/coach/f111/compose?'+new URLSearchParams(q).toString();}
  function composerContext(route){const cfg=D().composer||{},q=route.query||{};const level=/^L[1-4]$/.test(q.level||'')?q.level:'L1';const lowerMode=cfg.lowerModes?.[q.lower]?q.lower:'squat';const upperMode=cfg.upperModes?.[q.upper]?q.upper:'horizontal_pull';const coreDemand=cfg.coreDemands?.[q.core]?q.core:'anti_extension';const flags={includeExpandedMain:q.em==='1',includeExpandedSupport:q.es==='1',includeExpandedCore:q.ec==='1'};const probeSession=window.V15TemplateResolver.resolve('f111',{mode:'composer',level,lowerMode,upperMode,coreDemand,...flags});const stateKey=`${probeSession.familyId}-${level}`;const selections=window.V14State.getComposerSelections(stateKey);const resolvedSession=window.V15TemplateResolver.resolve('f111',{mode:'composer',level,lowerMode,upperMode,coreDemand,selections,...flags});const resolved=window.V14Composer.resolve({level,lowerMode,upperMode,coreDemand,selections,...flags});return {level,lowerMode,upperMode,coreDemand,stateKey,resolved,resolvedSession,...flags};}
  function composerLevelSwitch(ctx){return `<div class="composer-level-switch">${['L1','L2','L3','L4'].map(l=>`<a class="${ctx.level===l?'active':''}" href="${composeHref(ctx,{level:l})}">${l}</a>`).join('')}</div>`;}
  function composerMatrix(ctx){const cfg=D().composer||{},uppers=Object.entries(cfg.upperModes||{}),lowers=Object.entries(cfg.lowerModes||{});const head=`<div class="composer-matrix-corner">下肢 × 上肢</div>${uppers.map(([,u])=>`<div class="composer-matrix-head">${esc(u.name)}</div>`).join('')}`;const rows=lowers.map(([lk,l])=>`<div class="composer-matrix-rowhead"><b>${esc(l.name)}</b><small>${esc(l.subtitle||'')}</small></div>${uppers.map(([uk,u])=>`<a class="composer-matrix-cell ${ctx.lowerMode===lk&&ctx.upperMode===uk?'active':''}" href="${composeHref(ctx,{lower:lk,upper:uk})}"><span>${esc(l.name)}</span><i>×</i><b>${esc(u.name)}</b></a>`).join('')}`).join('');return `<div class="composer-matrix" aria-label="5 × 4 主模式矩阵">${head}${rows}</div>`;}
  function composerMobileSelectors(ctx){const cfg=D().composer||{};const options=(obj,current)=>Object.entries(obj).map(([k,v])=>`<option value="${esc(k)}" ${k===current?'selected':''}>${esc(v.name)}</option>`).join('');return `<div class="composer-mobile-selectors"><label>② 选下肢模式<select data-compose-query="lower">${options(cfg.lowerModes||{},ctx.lowerMode)}</select></label><label>③ 选上肢模式<select data-compose-query="upper">${options(cfg.upperModes||{},ctx.upperMode)}</select></label></div>`;}
  function composerRecovery(ctx){return D().sessionViews?.[`F111-01-${ctx.level}`]||{};}
  function buildComposerCopyPayload(ctx){const resolvedSession=ctx.resolvedSession||window.V15TemplateResolver.resolve('f111',{mode:'composer',level:ctx.level,lowerMode:ctx.lowerMode,upperMode:ctx.upperMode,coreDemand:ctx.coreDemand,selections:window.V14State?.getComposerSelections?.(ctx.stateKey)||{},includeExpandedMain:!!ctx.includeExpandedMain,includeExpandedSupport:!!ctx.includeExpandedSupport,includeExpandedCore:!!ctx.includeExpandedCore});const ids=resolvedSession.main.content.map(x=>x.actionId).filter(Boolean),summary=resolvedSession.anatomyContext||{primary:[],secondary:[],stabilizers:[]},result=resolvedSession.conflictContext||{issues:[]},view=composerRecovery(ctx),prepResolved=M.Prep.resolveComposerPrep(ctx);return {brand:'7Fit',sessionTitle:`自由组合｜${ctx.resolved.lower.name} + ${ctx.resolved.upper.name}`,recipeName:`${ctx.resolved.lower.name} + ${ctx.resolved.upper.name}`,level:ctx.level,summary:'F111 自由组合｜一下肢 + 一上肢 + 一支撑',foam:M.Foam.composerFoamItems(ctx).map(x=>({name:x.name,prescription:x.prescription})),warmups:M.Prep.resolvedItems(prepResolved).map(x=>({name:x.name,prescription:x.prescription})),slots:resolvedSession.main.content.map(x=>({slot:x.label,name:x.name,tier:x.tier,grade:x.grade,prescription:x.prescription||window.V14ModuleCopy?.prescriptionForAction?.(x.actionId,{level:ctx.level})||''})),muscles:{primary:summary.primary.slice(0,6),secondary:summary.secondary.slice(0,6),stabilizers:summary.stabilizers.slice(0,6)},recovery:(view.recovery||[]).map(x=>x.actions?.[0]?.name||x.text).filter(Boolean),postCardio:view.postCardio||'',conflicts:(result.issues||[]).map(x=>`${x.title}：${x.text}`)};}
  function render(route){
    const ctx=composerContext(route),cfg=D().composer||{},result=ctx.resolvedSession.conflictContext,allIds=ctx.resolvedSession.main.content.map(x=>x.actionId).filter(Boolean);
    const demands=Object.entries(cfg.coreDemands||{}).map(([k,v])=>`<a class="${ctx.coreDemand===k?'active':''}" href="${composeHref(ctx,{core:k})}">${esc(v.name)}</a>`).join('');
    const mainExpand=ctx.resolved.windows.main.expanded?.length?`<a class="composer-expand-link" href="${composeHref(ctx,{em:ctx.includeExpandedMain?null:'1'})}">${ctx.includeExpandedMain?'收起额外退阶':'展开额外退阶'}</a>`:'';
    const supportExpand=ctx.resolved.windows.support.expanded?.length?`<a class="composer-expand-link" href="${composeHref(ctx,{es:ctx.includeExpandedSupport?null:'1'})}">${ctx.includeExpandedSupport?'收起支撑扩展':'查看支撑扩展 '+ctx.resolved.windows.support.expanded.join(' / ')}</a>`:'';
    const coreExpand=ctx.resolved.windows.core.expanded?.length?`<a class="composer-expand-link" href="${composeHref(ctx,{ec:ctx.includeExpandedCore?null:'1'})}">${ctx.includeExpandedCore?'收起核心退阶':'查看更多核心退阶'}</a>`:'';
    const view=composerRecovery(ctx),recovery=(view.recovery||[]).map(x=>`<div class="flow-item"><b>${esc(x.actions?.[0]?.name||'恢复')}</b><span>${esc(x.text)}</span></div>`).join('');
    return coachModeSwitch('compose')+hero('自由组合编课','5 × 4 主模式矩阵：下肢推 / 下肢拉 / 臀伸 / 单腿蹲 / 单腿拉 × 水平拉 / 垂直拉 / 水平推 / 垂直推。Session L 决定推荐窗口，不把 T / S / CORE-L 机械锁死。',[ctx.level,'20 种基础组合','动态 D1 / D2','实时 Anatomy / Conflict'])+`<section class="section-card composer-builder"><div class="section-head"><div><h2>① 选择 Session Level</h2><p>先确定整节课阶段，再由系统给各模块不同的 Tier / Grade 候选窗口。</p></div></div>${composerLevelSwitch(ctx)}<div class="composer-builder-head"><div><h2>②–③ 选择主模式</h2><p>桌面端直接点击 5 × 4 主模式矩阵；手机端按下肢 → 上肢顺序选择。</p></div>${mainExpand}</div>${composerMatrix(ctx)}${composerMobileSelectors(ctx)}<div class="composer-current"><small>当前组合</small><b>${esc(ctx.level)}｜${esc(ctx.resolved.lower.name)} + ${esc(ctx.resolved.upper.name)}</b><span>${esc(ctx.resolved.compositionId)}</span></div></section>`+M.Prep.composerPrepHtml(ctx)+`<section class="section-card strength-card"><div class="section-head"><div><h2>1F｜STRENGTH</h2><p>A / B 选择主模式；C 使用独立 SUPPORT Grade；D1 / D2 自动补足；CORE 先选 Demand 再筛 Grade。</p></div><span class="time-badge">约 40–43 分钟</span></div>${M.Summary.render(allIds)}${M.ConflictView.render(result)}<div class="composer-subhead"><div><b>CORE Demand</b><span>先选功能，再选难度。</span></div><div class="core-demand-row">${demands}</div></div><div class="composer-window-actions">${supportExpand}${coreExpand}</div><div class="composer-slot-grid">${ctx.resolved.slots.map(x=>M.Slot.composerCard(ctx,x)).join('')}</div><div class="session-toolbar composer-copy-toolbar"><div></div><div class="session-toolbar-actions">${copyToolbar()}<button id="reset-composer" type="button">恢复系统推荐</button></div></div></section>`+`<section class="section-card"><div class="section-head"><div><h2>2F｜RECOVERY</h2><p>力量部分结束后一次上楼完成恢复。</p></div><span class="time-badge">约 5–8 分钟</span></div><div class="flow-grid recovery-grid">${recovery}</div></section><section class="post-cardio-note"><b>POST CARDIO ONLY</b><span>${esc(view.postCardio||'课后有氧独立执行。')}</span></section>`;
  }
  M.ComposerView={composeHref,composerContext,buildComposerCopyPayload,render};
})();
